"""Capability protocol + registry (DESIGN §3.3).

A `Capability` is a small, self-contained feature (checklist, ED-context, keybinds…)
that advertises tools to the LLM and handles their calls. Keeping features behind this
seam means adding one is dropping in a new capability, not editing the voice loop.

Required interface:
    tools()            -> list of tool schemas to advertise to the LLM
    run_tool(name, in) -> str result for a tool the LLM called

Optional hooks (duck-typed — a capability may omit them):
    on_event(event)      -> react to an EventBus event (e.g. an ED journal event)
    system_context()     -> a short string injected into the system prompt
    help_meta()          -> a HelpMeta describing the capability for the help subsystem
    help_vocabulary()    -> {kind: [valid values]} used by help's failure-recovery mode
                            (e.g. outfitting contributes {"module": [...module names]})

The registry aggregates tools() across capabilities and dispatches run_tool() to
whichever capability owns the named tool. It also *projects* the registered
capabilities' help metadata (see `HelpMeta`) so the help subsystem can speak an honest,
drift-free description of what the app can do — help output is templated from this data,
never generated by an LLM (Search Prompt 1).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional, Protocol, runtime_checkable


@runtime_checkable
class Capability(Protocol):
    def tools(self) -> list[dict]:
        """Tool schemas this capability advertises to the LLM."""
        ...

    def run_tool(self, name: str, inp: dict) -> str:
        """Execute one of this capability's tools; return a text result."""
        ...


# ---- help metadata (Search Prompt 1) ------------------------------------------------------
# Every user-facing capability may carry help metadata so the help subsystem can describe it
# without inventing anything. The metadata is the single source of truth: help templates
# only ever emit strings that came from here, which is what structurally prevents the
# companion from claiming a filter/slot/capability that doesn't exist.


@dataclass(frozen=True)
class Slot:
    """One refinement a capability accepts (a Spansh filter / tool arg), described for help.

      * `param`     — the tool argument / canonical Spansh parameter name.
      * `phrasings` — how a Commander might say it aloud (used as recovery vocabulary too).
      * `example`   — a real utterance that sets this slot.
      * `help_text` — one spoken sentence explaining the refinement.
    """
    param: str
    phrasings: tuple[str, ...]
    example: str
    help_text: str


@dataclass(frozen=True)
class HelpMeta:
    """A capability's self-description for the help subsystem.

      * `category`        — short spoken name for the capability ("outfitting").
      * `one_liner`       — one sentence: what it does.
      * `example`         — a real utterance that invokes it.
      * `slots`           — the refinements it accepts (may be empty).
      * `help_when_active`— optional extra guidance to speak while its dialog is in progress.
    """
    category: str
    one_liner: str
    example: str
    slots: tuple[Slot, ...] = field(default_factory=tuple)
    help_when_active: Optional[str] = None


_REQUIRED_META_FIELDS = ("category", "one_liner", "example")
_REQUIRED_SLOT_FIELDS = ("param", "example", "help_text")


def validate_help_meta(meta: HelpMeta) -> HelpMeta:
    """Reject help metadata missing any required field, so the registry never carries a
    half-described capability (the contract the later prompts harden). Raises ValueError
    with a specific message; returns the meta unchanged when complete."""
    if not isinstance(meta, HelpMeta):
        raise ValueError(f"help metadata must be a HelpMeta, got {type(meta).__name__}")
    for f in _REQUIRED_META_FIELDS:
        if not str(getattr(meta, f, "") or "").strip():
            raise ValueError(f"help metadata for '{meta.category or '?'}' is missing '{f}'")
    for i, slot in enumerate(meta.slots):
        for f in _REQUIRED_SLOT_FIELDS:
            if not str(getattr(slot, f, "") or "").strip():
                raise ValueError(
                    f"help metadata for '{meta.category}' slot #{i} is missing '{f}'")
        if not tuple(slot.phrasings):
            raise ValueError(
                f"help metadata for '{meta.category}' slot '{slot.param}' has no phrasings")
    return meta


def _capability_help(cap: "Capability") -> Optional[HelpMeta]:
    """The capability's HelpMeta, or None if it doesn't provide one (additive: capabilities
    without help metadata keep working)."""
    fn = getattr(cap, "help_meta", None)
    if fn is None:
        return None
    return fn()


class CapabilityRegistry:
    """Aggregates capabilities so the loop sees one tools() list and one run_tool().

    Also projects help metadata (help_entries / categories / vocabulary) and tracks how often
    each capability is used, so the help subsystem can rank what to mention. Registering a
    capability whose help metadata is incomplete fails loudly (the contract)."""

    def __init__(self, capabilities: Iterable[Capability] | None = None) -> None:
        self._caps: list[Capability] = []
        self._usage: list[int] = []
        for cap in capabilities or []:
            self.register(cap)

    def register(self, capability: Capability) -> None:
        meta = _capability_help(capability)
        if meta is not None:
            validate_help_meta(meta)  # reject incomplete help metadata at wiring time
        self._caps.append(capability)
        self._usage.append(0)

    def tools(self) -> list[dict]:
        """Every capability's tool schemas, in registration order."""
        out: list[dict] = []
        for cap in self._caps:
            out.extend(cap.tools())
        return out

    def run_tool(self, name: str, inp: dict) -> str:
        """Dispatch to the capability that advertises `name`. Unknown -> soft error
        string (the loop must survive any tool call, so we never raise). Usage of the
        owning capability is counted, so help can rank by what actually gets used."""
        for i, cap in enumerate(self._caps):
            if any(t.get("name") == name for t in cap.tools()):
                self._usage[i] += 1
                return cap.run_tool(name, inp)
        return f"Unknown tool: {name}"

    # -- help projection (Search Prompt 1) --------------------------------------
    def help_entries(self, *, exclude: Optional["Capability"] = None) -> list[HelpMeta]:
        """Every registered capability's HelpMeta, ranked most-used first (ties keep
        registration order). `exclude` drops one capability (help excludes itself so it
        doesn't headline its own idle listing)."""
        scored: list[tuple[int, int, HelpMeta]] = []
        for i, cap in enumerate(self._caps):
            if cap is exclude:
                continue
            meta = _capability_help(cap)
            if meta is None:
                continue
            scored.append((-self._usage[i], i, meta))
        scored.sort(key=lambda t: (t[0], t[1]))
        return [m for _u, _i, m in scored]

    def categories(self, *, exclude: Optional["Capability"] = None) -> list[str]:
        """Spoken category names of capabilities that carry help metadata, ranked by use."""
        return [m.category for m in self.help_entries(exclude=exclude)]

    def help_entry_for(self, category: str,
                       *, exclude: Optional["Capability"] = None) -> Optional[HelpMeta]:
        """The HelpMeta for a category by spoken name (case-insensitive), or None. Used to
        validate a topic before speaking about it, so help never names an unregistered one."""
        want = str(category or "").strip().lower()
        if not want:
            return None
        for m in self.help_entries(exclude=exclude):
            if m.category.strip().lower() == want:
                return m
        return None

    def vocabulary(self) -> dict[str, list[str]]:
        """Merged canonical value vocabulary contributed by capabilities via the optional
        `help_vocabulary()` hook (e.g. outfitting -> {"module": [...]}). This is what help's
        failure-recovery mode matches an unresolved term against, so a suggestion is always a
        real, registered value — never invented."""
        vocab: dict[str, list[str]] = {}
        for cap in self._caps:
            fn = getattr(cap, "help_vocabulary", None)
            if fn is None:
                continue
            for kind, values in (fn() or {}).items():
                bucket = vocab.setdefault(str(kind), [])
                for v in values:
                    if v not in bucket:
                        bucket.append(v)
        return vocab

    # -- optional hooks, forwarded to capabilities that implement them ----------
    def dispatch_event(self, event: dict) -> None:
        """Fan an EventBus event out to any capability with an on_event hook."""
        for cap in self._caps:
            handler = getattr(cap, "on_event", None)
            if handler is not None:
                handler(event)

    def system_context(self) -> Optional[str]:
        """Join the system_context() of any capability that provides one, or None."""
        parts = []
        for cap in self._caps:
            provider = getattr(cap, "system_context", None)
            if provider is not None:
                ctx = provider()
                if ctx:
                    parts.append(ctx)
        return "\n".join(parts) if parts else None
