"""Capability protocol + registry (DESIGN §3.3).

A `Capability` is a small, self-contained feature (checklist, ED-context, keybinds…)
that advertises tools to the LLM and handles their calls. Keeping features behind this
seam means adding one is dropping in a new capability, not editing the voice loop.

Required interface:
    tools()            -> list of tool schemas to advertise to the LLM
    run_tool(name, in) -> str result for a tool the LLM called

Optional hooks (duck-typed — a capability may omit them):
    on_event(event)      -> react to an EventBus event (e.g. an ED journal event)
    system_context()     -> a short string injected into the system prompt
    help_meta()          -> a HelpMeta describing the capability for the help subsystem
    help_vocabulary()    -> {kind: [valid values]} used by help's failure-recovery mode
                            (e.g. outfitting contributes {"module": [...module names]})

The registry aggregates tools() across capabilities and dispatches run_tool() to
whichever capability owns the named tool. It also *projects* the registered
capabilities' help metadata (see `HelpMeta`) so the help subsystem can speak an honest,
drift-free description of what the app can do — help output is templated from this data,
never generated by an LLM (Search Prompt 1).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Optional, Protocol, runtime_checkable


@runtime_checkable
class Capability(Protocol):
    def tools(self) -> list[dict]:
        """Tool schemas this capability advertises to the LLM."""
        ...

    def run_tool(self, name: str, inp: dict) -> str:
        """Execute one of this capability's tools; return a text result."""
        ...


# ---- help metadata (Search Prompt 1) ------------------------------------------------------
# Every user-facing capability may carry help metadata so the help subsystem can describe it
# without inventing anything. The metadata is the single source of truth: help templates
# only ever emit strings that came from here, which is what structurally prevents the
# companion from claiming a filter/slot/capability that doesn't exist.


@dataclass(frozen=True)
class Slot:
    """One refinement a capability accepts (a Spansh filter / tool arg), described for help.

      * `param`     — the tool argument, which IS the canonical Spansh parameter name for the
                      refinement (Search Prompt 2/3): query builders map slot -> `param`
                      directly, so the field the LLM fills, the field help advertises, and the
                      field Spansh receives are one string and cannot drift. Read it back via
                      `CapabilityRegistry.spansh_params_for` / `slot_for_param`.
      * `phrasings` — how a Commander might say it aloud (used as recovery vocabulary too).
      * `example`   — a real utterance that sets this slot.
      * `help_text` — one spoken sentence explaining the refinement.
    """
    param: str
    phrasings: tuple[str, ...]
    example: str
    help_text: str


@dataclass(frozen=True)
class HelpMeta:
    """A capability's self-description for the help subsystem.

      * `category`        — short spoken name for the capability ("outfitting").
      * `one_liner`       — one sentence: what it does.
      * `example`         — a real utterance that invokes it.
      * `slots`           — the refinements it accepts (may be empty).
      * `help_when_active`— optional extra guidance to speak while its dialog is in progress.
    """
    category: str
    one_liner: str
    example: str
    slots: tuple[Slot, ...] = field(default_factory=tuple)
    help_when_active: Optional[str] = None


_REQUIRED_META_FIELDS = ("category", "one_liner", "example")
_REQUIRED_SLOT_FIELDS = ("param", "example", "help_text")


def help_meta_problems(meta: object) -> list[str]:
    """Every reason `meta` is not COMPLETE help metadata, as human-readable strings (an empty
    list means complete). This is the *single* structural definition of the contract every
    registered category must satisfy — "one_liner, example, and a phrasing + help_text for
    every slot it introduces." Everything else that enforces the policy is built on this one
    function so it can't drift:

      * `validate_help_meta` raises on the first problem (wiring-time guard);
      * `CapabilityRegistry.contract_violations` collects problems across capabilities so a
        test can assert the REAL registry is clean — the guard every future category inherits.
    """
    if not isinstance(meta, HelpMeta):
        return [f"help metadata must be a HelpMeta, got {type(meta).__name__}"]
    problems: list[str] = []
    label = (str(meta.category or "").strip() or "?")
    for f in _REQUIRED_META_FIELDS:
        if not str(getattr(meta, f, "") or "").strip():
            problems.append(f"help metadata for '{label}' is missing '{f}'")
    for i, slot in enumerate(meta.slots):
        for f in _REQUIRED_SLOT_FIELDS:
            if not str(getattr(slot, f, "") or "").strip():
                problems.append(f"help metadata for '{label}' slot #{i} is missing '{f}'")
        if not tuple(slot.phrasings):
            problems.append(
                f"help metadata for '{label}' slot '{slot.param}' has no phrasings")
    return problems


def validate_help_meta(meta: HelpMeta) -> HelpMeta:
    """Reject help metadata missing any required field, so the registry never carries a
    half-described capability (the contract the later prompts harden). Raises ValueError
    with the first specific problem; returns the meta unchanged when complete."""
    problems = help_meta_problems(meta)
    if problems:
        raise ValueError(problems[0])
    return meta


def _capability_help(cap: "Capability") -> Optional[HelpMeta]:
    """The capability's HelpMeta, or None if it doesn't provide one (additive: capabilities
    without help metadata keep working)."""
    fn = getattr(cap, "help_meta", None)
    if fn is None:
        return None
    return fn()


class CapabilityRegistry:
    """Aggregates capabilities so the loop sees one tools() list and one run_tool().

    Also projects help metadata (help_entries / categories / vocabulary) and tracks how often
    each capability is used, so the help subsystem can rank what to mention. Registering a
    capability whose help metadata is incomplete fails loudly (the contract)."""

    def __init__(self, capabilities: Iterable[Capability] | None = None) -> None:
        self._caps: list[Capability] = []
        self._usage: list[int] = []
        for cap in capabilities or []:
            self.register(cap)

    def register(self, capability: Capability) -> None:
        meta = _capability_help(capability)
        if meta is not None:
            validate_help_meta(meta)  # reject incomplete help metadata at wiring time
        self._caps.append(capability)
        self._usage.append(0)

    def tools(self) -> list[dict]:
        """Every capability's tool schemas, in registration order."""
        out: list[dict] = []
        for cap in self._caps:
            out.extend(cap.tools())
        return out

    def run_tool(self, name: str, inp: dict) -> str:
        """Dispatch to the capability that advertises `name`. Unknown -> soft error
        string (the loop must survive any tool call, so we never raise). Usage of the
        owning capability is counted, so help can rank by what actually gets used."""
        for i, cap in enumerate(self._caps):
            if any(t.get("name") == name for t in cap.tools()):
                self._usage[i] += 1
                return cap.run_tool(name, inp)
        return f"Unknown tool: {name}"

    # -- contract enforcement (Search Prompt 2) ---------------------------------
    def contract_violations(self) -> list[str]:
        """Every registered capability's help-metadata contract problems, flattened (an empty
        list means every registered category is completely described).

        `register()` already refuses a capability whose help metadata is incomplete, so on a
        registry the app actually built this is normally empty. It exists so a test can assert
        the REAL registry satisfies the policy *structurally* — the guard every future category
        inherits: add a category with a slot missing its help_text and this stops returning []
        (and `register` stops accepting it), rather than the omission surviving in prose a
        future author skims."""
        out: list[str] = []
        for cap in self._caps:
            meta = _capability_help(cap)
            if meta is not None:
                out.extend(help_meta_problems(meta))
        return out

    # -- help projection (Search Prompt 1) --------------------------------------
    def help_entries(self, *, exclude: Optional["Capability"] = None) -> list[HelpMeta]:
        """Every registered capability's HelpMeta, ranked most-used first (ties keep
        registration order). `exclude` drops one capability (help excludes itself so it
        doesn't headline its own idle listing)."""
        scored: list[tuple[int, int, HelpMeta]] = []
        for i, cap in enumerate(self._caps):
            if cap is exclude:
                continue
            meta = _capability_help(cap)
            if meta is None:
                continue
            scored.append((-self._usage[i], i, meta))
        scored.sort(key=lambda t: (t[0], t[1]))
        return [m for _u, _i, m in scored]

    def categories(self, *, exclude: Optional["Capability"] = None) -> list[str]:
        """Spoken category names of capabilities that carry help metadata, ranked by use."""
        return [m.category for m in self.help_entries(exclude=exclude)]

    def help_entry_for(self, category: str,
                       *, exclude: Optional["Capability"] = None) -> Optional[HelpMeta]:
        """The HelpMeta for a category by spoken name (case-insensitive), or None. Used to
        validate a topic before speaking about it, so help never names an unregistered one."""
        want = str(category or "").strip().lower()
        if not want:
            return None
        for m in self.help_entries(exclude=exclude):
            if m.category.strip().lower() == want:
                return m
        return None

    # -- pure read helpers help consumes (Search Prompt 2) ----------------------
    # Read-only projections over registered metadata. Every value returned came from a
    # registered capability, so a consumer built on these can never speak a category, slot,
    # example, or Spansh field the registry doesn't actually carry.
    def examples(self, *, exclude: Optional["Capability"] = None) -> list[tuple[str, str]]:
        """`(category, example)` for every category carrying help metadata, ranked by use.
        The canonical example utterances help offers — each is a registered string, never
        generated."""
        return [(m.category, m.example) for m in self.help_entries(exclude=exclude)]

    def slots_for(self, category: str,
                  *, exclude: Optional["Capability"] = None) -> tuple[Slot, ...]:
        """The refinements (`Slot`s) a category accepts, in declared order — the data behind a
        "what can I add to this search?" answer. Empty tuple for an unknown category or one
        with no slots. Never invents a slot."""
        meta = self.help_entry_for(category, exclude=exclude)
        return tuple(meta.slots) if meta is not None else ()

    def spansh_params_for(self, category: str,
                          *, exclude: Optional["Capability"] = None) -> list[str]:
        """The canonical Spansh parameter names a category's slots map to, in declared order
        (`slot.param` IS that name — see `Slot`). This is the registry->Spansh field mapping in
        one place, so a query builder (Search Prompt 3) reads the fields straight from here and
        can't drift from what help advertises. Empty for an unknown category."""
        return [slot.param for slot in self.slots_for(category, exclude=exclude)]

    def slot_for_param(self, category: str, param: str,
                       *, exclude: Optional["Capability"] = None) -> Optional[Slot]:
        """The `Slot` in `category` whose canonical Spansh param is `param` (case-insensitive),
        or None — lets a query builder resolve a Spansh field back to its spoken phrasings and
        help text."""
        want = str(param or "").strip().lower()
        if not want:
            return None
        for slot in self.slots_for(category, exclude=exclude):
            if slot.param.strip().lower() == want:
                return slot
        return None

    def vocabulary(self) -> dict[str, list[str]]:
        """Merged canonical value vocabulary contributed by capabilities via the optional
        `help_vocabulary()` hook (e.g. outfitting -> {"module": [...]}). This is what help's
        failure-recovery mode matches an unresolved term against, so a suggestion is always a
        real, registered value — never invented."""
        vocab: dict[str, list[str]] = {}
        for cap in self._caps:
            fn = getattr(cap, "help_vocabulary", None)
            if fn is None:
                continue
            for kind, values in (fn() or {}).items():
                bucket = vocab.setdefault(str(kind), [])
                for v in values:
                    if v not in bucket:
                        bucket.append(v)
        return vocab

    # -- optional hooks, forwarded to capabilities that implement them ----------
    def dispatch_event(self, event: dict) -> None:
        """Fan an EventBus event out to any capability with an on_event hook."""
        for cap in self._caps:
            handler = getattr(cap, "on_event", None)
            if handler is not None:
                handler(event)

    def system_context(self) -> Optional[str]:
        """Join the system_context() of any capability that provides one, or None."""
        parts = []
        for cap in self._caps:
            provider = getattr(cap, "system_context", None)
            if provider is not None:
                ctx = provider()
                if ctx:
                    parts.append(ctx)
        return "\n".join(parts) if parts else None
