"""GENERATED — do not edit by hand.

The complete Elite Dangerous outfitting module table, baked from EDCD/FDevIDs
outfitting.csv (`tests/fixtures/fdevids_outfitting.csv`). Regenerate with:

    python scripts/gen_module_taxonomy.py

Each row: (id, name, category, sizes, mounts, ratings). `name` is the EXACT Spansh
station-search module-filter string. `covas/nav/modules.py` turns these into
ModuleSpec objects (adding friendly mishear aliases) and resolves against them.
"""
from __future__ import annotations

# 134 modules across weapon / standard / internal / utility.
MODULE_ROWS: tuple[tuple, ...] = (
    ('ax_missile_rack', 'AX Missile Rack', 'weapon', (2, 3), ('Fixed', 'Turret'), 'AB'),
    ('ax_multi_cannon', 'AX Multi-Cannon', 'weapon', (2, 3), ('Fixed', 'Turret'), 'CEF'),
    ('abrasion_blaster', 'Abrasion Blaster', 'weapon', (1,), ('Fixed', 'Turret'), 'D'),
    ('advanced_discovery_scanner', 'Advanced Discovery Scanner', 'internal', (1,), (), 'C'),
    ('advanced_docking_computer', 'Advanced Docking Computer', 'internal', (1,), (), 'E'),
    ('advanced_missile_rack', 'Advanced Missile Rack', 'weapon', (1, 2), ('Fixed',), 'B'),
    ('advanced_multi_cannon', 'Advanced Multi-Cannon', 'weapon', (1, 2), ('Fixed',), 'EF'),
    ('advanced_planetary_approach_suite', 'Advanced Planetary Approach Suite', 'internal', (1,), (), 'I'),
    ('advanced_plasma_accelerator', 'Advanced Plasma Accelerator', 'weapon', (3,), ('Fixed',), 'B'),
    ('auto_field_maintenance_unit', 'Auto Field-Maintenance Unit', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('basic_discovery_scanner', 'Basic Discovery Scanner', 'internal', (1,), (), 'E'),
    ('beam_laser', 'Beam Laser', 'weapon', (1, 2, 3, 4), ('Fixed', 'Gimbal', 'Turret'), 'ACDEF'),
    ('bi_weave_shield_generator', 'Bi-Weave Shield Generator', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'C'),
    ('burst_laser', 'Burst Laser', 'weapon', (1, 2, 3, 4), ('Fixed', 'Gimbal', 'Turret'), 'DEFG'),
    ('business_class_passenger_cabin', 'Business Class Passenger Cabin', 'internal', (3, 4, 5, 6), (), 'D'),
    ('cannon', 'Cannon', 'weapon', (1, 2, 3, 4), ('Fixed', 'Gimbal', 'Turret'), 'BCDEF'),
    ('cargo_rack', 'Cargo Rack', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'E'),
    ('cargo_scanner', 'Cargo Scanner', 'utility', (), (), 'ABCDE'),
    ('caustic_sink_launcher', 'Caustic Sink Launcher', 'utility', (), (), 'I'),
    ('chaff_launcher', 'Chaff Launcher', 'utility', (), (), 'I'),
    ('collector_limpet_controller', 'Collector Limpet Controller', 'internal', (1, 3, 5, 7), (), 'ABCDE'),
    ('concord_cannon', 'Concord Cannon', 'weapon', (2,), ('Gimbal',), 'D'),
    ('corrosion_resistant_cargo_rack', 'Corrosion Resistant Cargo Rack', 'internal', (1, 4), (), 'EF'),
    ('cytoscrambler_burst_laser', 'Cytoscrambler Burst Laser', 'weapon', (1,), ('Fixed',), 'F'),
    ('decontamination_limpet_controller', 'Decontamination Limpet Controller', 'internal', (1, 3, 5, 7), (), 'E'),
    ('detailed_surface_scanner', 'Detailed Surface Scanner', 'internal', (1,), (), 'I'),
    ('economy_class_passenger_cabin', 'Economy Class Passenger Cabin', 'internal', (2, 3, 4, 5, 6), (), 'E'),
    ('electronic_countermeasure', 'Electronic Countermeasure', 'utility', (), (), 'F'),
    ('enforcer_cannon', 'Enforcer Cannon', 'weapon', (1,), ('Fixed',), 'F'),
    ('enhanced_ax_missile_rack', 'Enhanced AX Missile Rack', 'weapon', (2, 3), ('Fixed', 'Turret'), 'BDE'),
    ('enhanced_ax_multi_cannon', 'Enhanced AX Multi-Cannon', 'weapon', (2, 3), ('Fixed', 'Gimbal', 'Turret'), 'BCDE'),
    ('enhanced_performance_thrusters', 'Enhanced Performance Thrusters', 'standard', (2, 3), (), 'A'),
    ('enhanced_xeno_scanner', 'Enhanced Xeno Scanner', 'utility', (), (), 'C'),
    ('enzyme_missile_rack', 'Enzyme Missile Rack', 'weapon', (2,), ('Fixed',), 'B'),
    ('experimental_weapon_stabiliser', 'Experimental Weapon Stabiliser', 'internal', (3, 5), (), 'F'),
    ('fighter_hangar', 'Fighter Hangar', 'internal', (5, 6, 7), (), 'D'),
    ('first_class_passenger_cabin', 'First Class Passenger Cabin', 'internal', (4, 5, 6), (), 'C'),
    ('fragment_cannon', 'Fragment Cannon', 'weapon', (1, 2, 3), ('Fixed', 'Gimbal', 'Turret'), 'ACDE'),
    ('frame_shift_drive', 'Frame Shift Drive', 'standard', (2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('frame_shift_drive_sco', 'Frame Shift Drive (SCO)', 'standard', (2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('frame_shift_drive_interdictor', 'Frame Shift Drive Interdictor', 'internal', (1, 2, 3, 4), (), 'ABCDE'),
    ('frame_shift_wake_scanner', 'Frame Shift Wake Scanner', 'utility', (), (), 'ABCDE'),
    ('fuel_scoop', 'Fuel Scoop', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('fuel_tank', 'Fuel Tank', 'standard', (1, 2, 3, 4, 5, 6, 7, 8), (), 'C'),
    ('fuel_transfer_limpet_controller', 'Fuel Transfer Limpet Controller', 'internal', (1, 3, 5, 7), (), 'ABCDE'),
    ('guardian_fsd_booster', 'Guardian FSD Booster', 'internal', (1, 2, 3, 4, 5), (), 'H'),
    ('guardian_gauss_cannon', 'Guardian Gauss Cannon', 'weapon', (1, 2), ('Fixed',), 'BD'),
    ('guardian_hull_reinforcement', 'Guardian Hull Reinforcement', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('guardian_hybrid_power_distributor', 'Guardian Hybrid Power Distributor', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'A'),
    ('guardian_hybrid_power_plant', 'Guardian Hybrid Power Plant', 'internal', (2, 3, 4, 5, 6, 7, 8), (), 'A'),
    ('guardian_module_reinforcement', 'Guardian Module Reinforcement', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('guardian_nanite_torpedo_pylon', 'Guardian Nanite Torpedo Pylon', 'weapon', (2, 3), ('Fixed',), 'I'),
    ('guardian_plasma_charger', 'Guardian Plasma Charger', 'weapon', (1, 2, 3), ('Fixed', 'Turret'), 'BCDEF'),
    ('guardian_shard_cannon', 'Guardian Shard Cannon', 'weapon', (1, 2, 3), ('Fixed', 'Turret'), 'ACDF'),
    ('guardian_shield_reinforcement', 'Guardian Shield Reinforcement', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('hatch_breaker_limpet_controller', 'Hatch Breaker Limpet Controller', 'internal', (1, 3, 5, 7), (), 'ABCDEI'),
    ('heat_sink_launcher', 'Heat Sink Launcher', 'utility', (), (), 'I'),
    ('hull_reinforcement_package', 'Hull Reinforcement Package', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('imperial_hammer_rail_gun', 'Imperial Hammer Rail Gun', 'weapon', (2,), ('Fixed',), 'B'),
    ('intermediate_discovery_scanner', 'Intermediate Discovery Scanner', 'internal', (1,), (), 'D'),
    ('kill_warrant_scanner', 'Kill Warrant Scanner', 'utility', (), (), 'ABCDE'),
    ('life_support', 'Life Support', 'standard', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('lightweight_alloy', 'Lightweight Alloy', 'standard', (1,), (), 'CI'),
    ('luxury_class_passenger_cabin', 'Luxury Class Passenger Cabin', 'internal', (5, 6), (), 'B'),
    ('meta_alloy_hull_reinforcement', 'Meta Alloy Hull Reinforcement', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('military_grade_composite', 'Military Grade Composite', 'standard', (1,), (), 'AI'),
    ('mine_launcher', 'Mine Launcher', 'weapon', (1, 2), ('Fixed',), 'I'),
    ('mining_lance', 'Mining Lance', 'weapon', (1,), ('Fixed',), 'D'),
    ('mining_laser', 'Mining Laser', 'weapon', (1, 2), ('Fixed', 'Turret'), 'D'),
    ('mining_multi_limpet_controller', 'Mining Multi Limpet Controller', 'internal', (3,), (), 'CE'),
    ('mining_volley_repeater', 'Mining Volley Repeater', 'weapon', (3,), ('Fixed',), 'C'),
    ('mirrored_surface_composite', 'Mirrored Surface Composite', 'standard', (1,), (), 'AI'),
    ('missile_rack', 'Missile Rack', 'weapon', (1, 2, 3), ('Fixed',), 'AB'),
    ('mk_ii_ablative_lightweight_alloys', 'Mk II Ablative Lightweight Alloys', 'standard', (1,), (), 'C'),
    ('mk_ii_ablative_military_grade_composite', 'Mk II Ablative Military Grade Composite', 'standard', (1,), (), 'A'),
    ('mk_ii_ablative_mirrored_surface_composite', 'Mk II Ablative Mirrored Surface Composite', 'standard', (1,), (), 'A'),
    ('mk_ii_ablative_reactive_surface_composite', 'Mk II Ablative Reactive Surface Composite', 'standard', (1,), (), 'A'),
    ('mk_ii_ablative_reinforced_alloys', 'Mk II Ablative Reinforced Alloys', 'standard', (1,), (), 'B'),
    ('mk_ii_agile_boost_thrusters', 'Mk II Agile Boost Thrusters', 'standard', (5,), (), 'A'),
    ('mk_ii_cargo_rack', 'Mk II Cargo Rack', 'internal', (7, 8), (), 'D'),
    ('mk_ii_gravity_optimised_thrusters', 'Mk II Gravity Optimised Thrusters', 'standard', (7,), (), 'A'),
    ('mk_ii_mining_multi_limpet_controller', 'Mk II Mining Multi-Limpet Controller', 'internal', (5,), (), 'A'),
    ('mk_ii_plasma_shock_accelerator', 'Mk II Plasma Shock Accelerator', 'weapon', (3,), ('Fixed',), 'B'),
    ('mk_ii_supercharge_optimised_frame_shift_drive_sco', 'Mk II Supercharge Optimised Frame Shift Drive (SCO)', 'standard', (8,), (), 'A'),
    ('mkii_business_class_passenger_cabin', 'MkII Business Class Passenger Cabin', 'internal', (3, 4, 5), (), 'C'),
    ('mkii_economy_class_passenger_cabin', 'MkII Economy Class Passenger Cabin', 'internal', (2, 3, 4, 5), (), 'D'),
    ('module_reinforcement_package', 'Module Reinforcement Package', 'internal', (1, 2, 3, 4, 5), (), 'DE'),
    ('multi_cannon', 'Multi-Cannon', 'weapon', (1, 2, 3, 4), ('Fixed', 'Gimbal', 'Turret'), 'ACEFG'),
    ('operations_multi_limpet_controller', 'Operations Multi Limpet Controller', 'internal', (3,), (), 'BC'),
    ('pacifier_frag_cannon', 'Pacifier Frag-Cannon', 'weapon', (3,), ('Fixed',), 'C'),
    ('pack_hound_missile_rack', 'Pack-Hound Missile Rack', 'weapon', (2,), ('Fixed',), 'B'),
    ('planetary_approach_suite', 'Planetary Approach Suite', 'internal', (1,), (), 'I'),
    ('planetary_vehicle_hangar', 'Planetary Vehicle Hangar', 'internal', (2, 4, 6), (), 'GH'),
    ('plasma_accelerator', 'Plasma Accelerator', 'weapon', (2, 3, 4), ('Fixed',), 'ABC'),
    ('point_defence', 'Point Defence', 'utility', (), (), 'I'),
    ('power_distributor', 'Power Distributor', 'standard', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('power_plant', 'Power Plant', 'standard', (2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('prismatic_shield_generator', 'Prismatic Shield Generator', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'A'),
    ('prospector_limpet_controller', 'Prospector Limpet Controller', 'internal', (1, 3, 5, 7), (), 'ABCDE'),
    ('pulse_disruptor_laser', 'Pulse Disruptor Laser', 'weapon', (2,), ('Fixed',), 'E'),
    ('pulse_laser', 'Pulse Laser', 'weapon', (1, 2, 3, 4), ('Fixed', 'Gimbal', 'Turret'), 'ADEFG'),
    ('pulse_wave_analyser', 'Pulse Wave Analyser', 'utility', (), (), 'ABCDE'),
    ('pulse_wave_xeno_scanner', 'Pulse Wave Xeno Scanner', 'utility', (), (), 'C'),
    ('rail_gun', 'Rail Gun', 'weapon', (1, 2), ('Fixed',), 'BD'),
    ('reactive_surface_composite', 'Reactive Surface Composite', 'standard', (1,), (), 'AI'),
    ('recon_limpet_controller', 'Recon Limpet Controller', 'internal', (1, 3, 5, 7), (), 'E'),
    ('refinery', 'Refinery', 'internal', (1, 2, 3, 4), (), 'ABCDE'),
    ('reinforced_alloy', 'Reinforced Alloy', 'standard', (1,), (), 'BI'),
    ('remote_release_flak_launcher', 'Remote Release Flak Launcher', 'weapon', (2,), ('Fixed', 'Turret'), 'B'),
    ('remote_release_flechette_launcher', 'Remote Release Flechette Launcher', 'weapon', (2,), ('Fixed', 'Turret'), 'B'),
    ('repair_limpet_controller', 'Repair Limpet Controller', 'internal', (1, 3, 5, 7), (), 'ABCDE'),
    ('rescue_multi_limpet_controller', 'Rescue Multi Limpet Controller', 'internal', (3,), (), 'CD'),
    ('research_limpet_controller', 'Research Limpet Controller', 'internal', (1,), (), 'E'),
    ('retributor_beam_laser', 'Retributor Beam Laser', 'weapon', (1,), ('Fixed',), 'E'),
    ('rocket_propelled_fsd_disruptor', 'Rocket Propelled FSD Disruptor', 'weapon', (2,), ('Fixed',), 'B'),
    ('seeker_missile_rack', 'Seeker Missile Rack', 'weapon', (1, 2, 3), ('Fixed',), 'AB'),
    ('seismic_charge_launcher', 'Seismic Charge Launcher', 'weapon', (2,), ('Fixed', 'Turret'), 'B'),
    ('sensors', 'Sensors', 'standard', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('shield_booster', 'Shield Booster', 'utility', (), (), 'ABCDE'),
    ('shield_cell_bank', 'Shield Cell Bank', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('shield_generator', 'Shield Generator', 'internal', (1, 2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('shock_cannon', 'Shock Cannon', 'weapon', (1, 2, 3), ('Fixed', 'Gimbal', 'Turret'), 'CDEF'),
    ('shock_mine_launcher', 'Shock Mine Launcher', 'weapon', (1,), ('Fixed',), 'I'),
    ('shutdown_field_neutraliser', 'Shutdown Field Neutraliser', 'utility', (), (), 'F'),
    ('standard_docking_computer', 'Standard Docking Computer', 'internal', (1,), (), 'E'),
    ('sub_surface_displacement_missile', 'Sub-Surface Displacement Missile', 'weapon', (1, 2), ('Fixed', 'Turret'), 'B'),
    ('sub_surface_extraction_missile', 'Sub-Surface Extraction Missile', 'weapon', (2,), ('Fixed',), 'B'),
    ('supercruise_assist', 'Supercruise Assist', 'internal', (1,), (), 'E'),
    ('thargoid_pulse_neutraliser', 'Thargoid Pulse Neutraliser', 'utility', (), (), 'E'),
    ('thrusters', 'Thrusters', 'standard', (2, 3, 4, 5, 6, 7, 8), (), 'ABCDE'),
    ('torpedo_pylon', 'Torpedo Pylon', 'weapon', (1, 2, 3), ('Fixed',), 'I'),
    ('universal_multi_limpet_controller', 'Universal Multi Limpet Controller', 'internal', (7,), (), 'AC'),
    ('xeno_multi_limpet_controller', 'Xeno Multi Limpet Controller', 'internal', (3,), (), 'BC'),
    ('xeno_scanner', 'Xeno Scanner', 'utility', (), (), 'E'),
)
