"""GENERATED — do not edit by hand.

Elite Dangerous ship-specification table (issue #83), baked from the maintained
EDCD/coriolis-data ship JSON (https://github.com/EDCD/coriolis-data, ships/*.json) —
the same lineage Coriolis/EDSY use, and where newer hulls get real numbers instead of
the model's training-cutoff guesses. Regenerate (needs network) with:

    C:/dev/COVAS++/.venv/Scripts/python.exe scripts/gen_ship_specs.py

Keyed by the canonical ship id in `covas/nav/ships.py`, so a resolved hull looks its
spec straight up. `covas/nav/ship_specs.py` wraps these dicts and does the lookup.

Fields: manufacturer; pad_size (1=S 2=M 3=L); hull_mass (t); fuel_capacity (t, main
tank); max_cargo (t, every cargo-capable optional slot as a cargo rack); crew seats;
top_speed / boost_speed (m/s); base_shield / base_armour; masslock factor; core (7
internal sizes: power plant, thrusters, FSD, life support, power distributor, sensors,
fuel tank); hardpoints (weapon mount sizes, 1=S 2=M 3=L 4=H); utilities (utility mount
count); optional ((size, kind) per optional internal — kind '' normal / 'military' /
'cargo'). Jump range is deliberately absent: it is fit-dependent, not a hull constant —
the tool defers to the live loadout / web search for it.
"""
from __future__ import annotations

# 47 hulls. CORE_ORDER = power plant, thrusters, FSD, life support, power
# distributor, sensors, fuel tank.
SHIP_SPECS: dict[str, dict] = {
    'adder': {
        'name': 'Adder', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 1, 'hull_mass': 35.0, 'fuel_capacity': 8, 'max_cargo': 30,
        'crew': 2, 'top_speed': 220, 'boost_speed': 320, 'base_shield': 60, 'base_armour': 90, 'masslock': 7,
        'core': (3, 3, 3, 1, 2, 3, 3),
        'hardpoints': (2, 1, 1), 'utilities': 2,
        'optional': ((3, ''), (3, ''), (2, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'alliance_challenger': {
        'name': 'Alliance Challenger', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 450.0, 'fuel_capacity': 16, 'max_cargo': 154,
        'crew': 2, 'top_speed': 204, 'boost_speed': 310, 'base_shield': 220, 'base_armour': 300, 'masslock': 13,
        'core': (6, 6, 5, 5, 6, 4, 4),
        'hardpoints': (3, 2, 2, 2, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (3, ''), (3, ''), (2, ''), (2, ''), (4, 'military'), (4, 'military'), (4, 'military'), (1, '')),
    },
    'alliance_chieftain': {
        'name': 'Alliance Chieftain', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 400.0, 'fuel_capacity': 16, 'max_cargo': 122,
        'crew': 2, 'top_speed': 230, 'boost_speed': 330, 'base_shield': 200, 'base_armour': 280, 'masslock': 13,
        'core': (6, 6, 5, 5, 6, 4, 4),
        'hardpoints': (3, 3, 2, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (4, ''), (2, ''), (2, ''), (4, 'military'), (4, 'military'), (4, 'military'), (1, '')),
    },
    'alliance_crusader': {
        'name': 'Alliance Crusader', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 500.0, 'fuel_capacity': 16, 'max_cargo': 122,
        'crew': 4, 'top_speed': 180, 'boost_speed': 300, 'base_shield': 200, 'base_armour': 300, 'masslock': 13,
        'core': (6, 6, 5, 5, 6, 4, 4),
        'hardpoints': (3, 2, 2, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (3, ''), (3, ''), (2, ''), (2, ''), (4, 'military'), (4, 'military'), (4, 'military'), (1, '')),
    },
    'anaconda': {
        'name': 'Anaconda', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 3, 'hull_mass': 400.0, 'fuel_capacity': 32, 'max_cargo': 470,
        'crew': 4, 'top_speed': 180, 'boost_speed': 240, 'base_shield': 350, 'base_armour': 525, 'masslock': 23,
        'core': (8, 7, 6, 5, 8, 8, 5),
        'hardpoints': (4, 3, 3, 3, 2, 2, 1, 1), 'utilities': 8,
        'optional': ((7, ''), (6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, ''), (5, 'military'), (4, ''), (4, ''), (4, ''), (2, ''), (1, '')),
    },
    'asp_explorer': {
        'name': 'Asp Explorer', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 280.0, 'fuel_capacity': 32, 'max_cargo': 130,
        'crew': 2, 'top_speed': 250, 'boost_speed': 340, 'base_shield': 140, 'base_armour': 210, 'masslock': 11,
        'core': (5, 5, 5, 4, 4, 5, 5),
        'hardpoints': (2, 2, 1, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (3, ''), (3, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'asp_scout': {
        'name': 'Asp Scout', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 150.0, 'fuel_capacity': 16, 'max_cargo': 74,
        'crew': 2, 'top_speed': 220, 'boost_speed': 300, 'base_shield': 120, 'base_armour': 180, 'masslock': 8,
        'core': (4, 4, 4, 3, 4, 4, 4),
        'hardpoints': (2, 2, 1, 1), 'utilities': 2,
        'optional': ((5, ''), (4, ''), (3, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'beluga': {
        'name': 'Beluga Liner', 'manufacturer': 'Saud Kruger',
        'pad_size': 3, 'hull_mass': 950.0, 'fuel_capacity': 128, 'max_cargo': 370,
        'crew': 4, 'top_speed': 200, 'boost_speed': 280, 'base_shield': 280, 'base_armour': 280, 'masslock': 18,
        'core': (6, 7, 7, 8, 6, 5, 7),
        'hardpoints': (2, 2, 2, 2, 2), 'utilities': 6,
        'optional': ((6, ''), (6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (4, ''), (3, ''), (3, ''), (3, ''), (3, ''), (1, '')),
    },
    'caspian': {
        'name': 'Caspian Explorer', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 3, 'hull_mass': 950.0, 'fuel_capacity': 128, 'max_cargo': 434,
        'crew': 4, 'top_speed': 210, 'boost_speed': 290, 'base_shield': 500, 'base_armour': 345, 'masslock': 19,
        'core': (8, 7, 8, 5, 7, 8, 7),
        'hardpoints': (3, 2, 2, 2, 2, 2, 2), 'utilities': 6,
        'optional': ((7, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, ''), (5, ''), (4, ''), (4, ''), (3, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'cobra_mk3': {
        'name': 'Cobra MkIII', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 180.0, 'fuel_capacity': 16, 'max_cargo': 64,
        'crew': 2, 'top_speed': 280, 'boost_speed': 400, 'base_shield': 80, 'base_armour': 120, 'masslock': 8,
        'core': (4, 4, 4, 3, 3, 3, 4),
        'hardpoints': (2, 2, 1, 1), 'utilities': 2,
        'optional': ((4, ''), (4, ''), (4, ''), (2, ''), (2, ''), (2, ''), (1, ''), (1, '')),
    },
    'cobra_mk4': {
        'name': 'Cobra MkIV', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 210.0, 'fuel_capacity': 16, 'max_cargo': 92,
        'crew': 2, 'top_speed': 200, 'boost_speed': 300, 'base_shield': 120, 'base_armour': 120, 'masslock': 8,
        'core': (4, 4, 4, 3, 3, 3, 4),
        'hardpoints': (2, 2, 1, 1, 1), 'utilities': 2,
        'optional': ((4, ''), (4, ''), (4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (2, ''), (1, ''), (1, '')),
    },
    'cobra_mk5': {
        'name': 'Cobra MkV', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 150.0, 'fuel_capacity': 16, 'max_cargo': 110,
        'crew': 3, 'top_speed': 291, 'boost_speed': 412, 'base_shield': 160, 'base_armour': 180, 'masslock': 8,
        'core': (4, 4, 4, 3, 4, 3, 4),
        'hardpoints': (2, 2, 2, 1, 1), 'utilities': 4,
        'optional': ((5, ''), (4, ''), (4, ''), (4, ''), (3, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'corsair': {
        'name': 'Corsair', 'manufacturer': 'Gutamaya',
        'pad_size': 2, 'hull_mass': 265.0, 'fuel_capacity': 32, 'max_cargo': 318,
        'crew': 2, 'top_speed': 280, 'boost_speed': 355, 'base_shield': 235, 'base_armour': 270, 'masslock': 17,
        'core': (7, 7, 5, 4, 7, 6, 5),
        'hardpoints': (3, 3, 3, 2, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, ''), (4, ''), (3, ''), (2, ''), (1, '')),
    },
    'diamondback_explorer': {
        'name': 'Diamondback Explorer', 'manufacturer': 'Lakon',
        'pad_size': 1, 'hull_mass': 260.0, 'fuel_capacity': 32, 'max_cargo': 60,
        'crew': 1, 'top_speed': 260, 'boost_speed': 340, 'base_shield': 150, 'base_armour': 150, 'masslock': 10,
        'core': (4, 4, 5, 3, 4, 3, 5),
        'hardpoints': (3, 2, 2), 'utilities': 4,
        'optional': ((4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (2, ''), (1, ''), (1, '')),
    },
    'diamondback_scout': {
        'name': 'Diamondback Scout', 'manufacturer': 'Lakon',
        'pad_size': 1, 'hull_mass': 170.0, 'fuel_capacity': 16, 'max_cargo': 32,
        'crew': 1, 'top_speed': 280, 'boost_speed': 380, 'base_shield': 120, 'base_armour': 120, 'masslock': 8,
        'core': (4, 4, 4, 2, 3, 2, 4),
        'hardpoints': (2, 2, 1, 1), 'utilities': 4,
        'optional': ((3, ''), (3, ''), (3, ''), (2, ''), (1, ''), (1, '')),
    },
    'dolphin': {
        'name': 'Dolphin', 'manufacturer': 'Saud Kruger',
        'pad_size': 1, 'hull_mass': 140.0, 'fuel_capacity': 16, 'max_cargo': 88,
        'crew': 1, 'top_speed': 250, 'boost_speed': 350, 'base_shield': 110, 'base_armour': 110, 'masslock': 9,
        'core': (4, 5, 4, 4, 3, 3, 4),
        'hardpoints': (1, 1), 'utilities': 3,
        'optional': ((5, ''), (4, ''), (4, ''), (3, ''), (2, ''), (2, ''), (2, ''), (1, ''), (1, '')),
    },
    'eagle': {
        'name': 'Eagle', 'manufacturer': 'Core Dynamics',
        'pad_size': 1, 'hull_mass': 50.0, 'fuel_capacity': 4, 'max_cargo': 20,
        'crew': 1, 'top_speed': 240, 'boost_speed': 350, 'base_shield': 60, 'base_armour': 40, 'masslock': 6,
        'core': (2, 3, 3, 1, 2, 2, 2),
        'hardpoints': (1, 1, 1), 'utilities': 1,
        'optional': ((3, ''), (2, ''), (2, 'military'), (1, ''), (1, ''), (1, ''), (1, '')),
    },
    'federal_assault_ship': {
        'name': 'Federal Assault Ship', 'manufacturer': 'Core Dynamics',
        'pad_size': 2, 'hull_mass': 480.0, 'fuel_capacity': 16, 'max_cargo': 98,
        'crew': 2, 'top_speed': 210, 'boost_speed': 350, 'base_shield': 200, 'base_armour': 300, 'masslock': 14,
        'core': (6, 6, 5, 5, 6, 4, 4),
        'hardpoints': (3, 3, 2, 2), 'utilities': 4,
        'optional': ((5, ''), (5, ''), (4, ''), (4, 'military'), (4, 'military'), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'federal_corvette': {
        'name': 'Federal Corvette', 'manufacturer': 'Core Dynamics',
        'pad_size': 3, 'hull_mass': 900.0, 'fuel_capacity': 32, 'max_cargo': 618,
        'crew': 4, 'top_speed': 200, 'boost_speed': 260, 'base_shield': 555, 'base_armour': 370, 'masslock': 24,
        'core': (8, 7, 6, 5, 8, 8, 5),
        'hardpoints': (4, 4, 3, 2, 2, 1, 1), 'utilities': 8,
        'optional': ((7, ''), (7, ''), (7, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, 'military'), (5, 'military'), (4, ''), (4, ''), (3, ''), (1, '')),
    },
    'federal_dropship': {
        'name': 'Federal Dropship', 'manufacturer': 'Core Dynamics',
        'pad_size': 2, 'hull_mass': 580.0, 'fuel_capacity': 16, 'max_cargo': 166,
        'crew': 2, 'top_speed': 180, 'boost_speed': 300, 'base_shield': 200, 'base_armour': 300, 'masslock': 14,
        'core': (6, 6, 5, 5, 6, 4, 4),
        'hardpoints': (3, 2, 2, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (5, ''), (4, ''), (4, 'military'), (4, 'military'), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'federal_gunship': {
        'name': 'Federal Gunship', 'manufacturer': 'Core Dynamics',
        'pad_size': 2, 'hull_mass': 580.0, 'fuel_capacity': 16, 'max_cargo': 170,
        'crew': 2, 'top_speed': 170, 'boost_speed': 280, 'base_shield': 250, 'base_armour': 350, 'masslock': 14,
        'core': (6, 6, 5, 5, 7, 5, 4),
        'hardpoints': (3, 2, 2, 2, 2, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (5, ''), (4, 'military'), (4, 'military'), (4, 'military'), (2, ''), (2, ''), (1, '')),
    },
    'fer_de_lance': {
        'name': 'Fer-de-Lance', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 2, 'hull_mass': 250.0, 'fuel_capacity': 8, 'max_cargo': 72,
        'crew': 2, 'top_speed': 260, 'boost_speed': 350, 'base_shield': 300, 'base_armour': 225, 'masslock': 12,
        'core': (6, 5, 4, 4, 6, 4, 3),
        'hardpoints': (4, 2, 2, 2, 2), 'utilities': 6,
        'optional': ((5, ''), (4, ''), (4, ''), (2, ''), (1, ''), (1, '')),
    },
    'hauler': {
        'name': 'Hauler', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 1, 'hull_mass': 14.0, 'fuel_capacity': 4, 'max_cargo': 26,
        'crew': 1, 'top_speed': 200, 'boost_speed': 300, 'base_shield': 50, 'base_armour': 100, 'masslock': 6,
        'core': (2, 2, 2, 1, 1, 1, 2),
        'hardpoints': (1,), 'utilities': 2,
        'optional': ((3, ''), (3, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'imperial_clipper': {
        'name': 'Imperial Clipper', 'manufacturer': 'Gutamaya',
        'pad_size': 3, 'hull_mass': 400.0, 'fuel_capacity': 16, 'max_cargo': 250,
        'crew': 2, 'top_speed': 300, 'boost_speed': 380, 'base_shield': 180, 'base_armour': 270, 'masslock': 12,
        'core': (6, 6, 5, 5, 6, 5, 4),
        'hardpoints': (3, 3, 2, 2), 'utilities': 4,
        'optional': ((7, ''), (6, ''), (4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'imperial_courier': {
        'name': 'Imperial Courier', 'manufacturer': 'Gutamaya',
        'pad_size': 1, 'hull_mass': 35.0, 'fuel_capacity': 8, 'max_cargo': 34,
        'crew': 1, 'top_speed': 280, 'boost_speed': 380, 'base_shield': 200, 'base_armour': 80, 'masslock': 7,
        'core': (4, 3, 3, 1, 3, 2, 3),
        'hardpoints': (2, 2, 2), 'utilities': 4,
        'optional': ((3, ''), (3, ''), (2, ''), (2, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'imperial_cutter': {
        'name': 'Imperial Cutter', 'manufacturer': 'Gutamaya',
        'pad_size': 3, 'hull_mass': 1100.0, 'fuel_capacity': 64, 'max_cargo': 794,
        'crew': 4, 'top_speed': 200, 'boost_speed': 320, 'base_shield': 600, 'base_armour': 400, 'masslock': 27,
        'core': (8, 8, 7, 7, 7, 7, 6),
        'hardpoints': (4, 3, 3, 2, 2, 2, 2), 'utilities': 8,
        'optional': ((8, ''), (8, ''), (6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, 'military'), (5, 'military'), (4, ''), (3, ''), (1, '')),
    },
    'imperial_eagle': {
        'name': 'Imperial Eagle', 'manufacturer': 'Gutamaya',
        'pad_size': 1, 'hull_mass': 50.0, 'fuel_capacity': 4, 'max_cargo': 20,
        'crew': 1, 'top_speed': 300, 'boost_speed': 400, 'base_shield': 80, 'base_armour': 60, 'masslock': 6,
        'core': (3, 3, 3, 1, 2, 2, 2),
        'hardpoints': (2, 1, 1), 'utilities': 1,
        'optional': ((3, ''), (2, ''), (2, 'military'), (1, ''), (1, ''), (1, ''), (1, '')),
    },
    'keelback': {
        'name': 'Keelback', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 180.0, 'fuel_capacity': 16, 'max_cargo': 98,
        'crew': 2, 'top_speed': 200, 'boost_speed': 300, 'base_shield': 135, 'base_armour': 270, 'masslock': 8,
        'core': (4, 4, 4, 1, 3, 2, 4),
        'hardpoints': (2, 2, 1, 1), 'utilities': 3,
        'optional': ((5, ''), (5, ''), (4, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'kestrel': {
        'name': 'Kestrel Mk II', 'manufacturer': 'Core Dynamics',
        'pad_size': 1, 'hull_mass': 190.0, 'fuel_capacity': 16, 'max_cargo': 70,
        'crew': 1, 'top_speed': 271, 'boost_speed': 360, 'base_shield': 225, 'base_armour': 70, 'masslock': 10,
        'core': (5, 5, 4, 1, 5, 2, 4),
        'hardpoints': (3, 3, 3, 1, 1), 'utilities': 4,
        'optional': ((5, ''), (4, ''), (4, 'military'), (3, ''), (2, ''), (2, ''), (2, ''), (1, '')),
    },
    'krait_mk2': {
        'name': 'Krait MkII', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 2, 'hull_mass': 320.0, 'fuel_capacity': 32, 'max_cargo': 230,
        'crew': 3, 'top_speed': 240, 'boost_speed': 330, 'base_shield': 220, 'base_armour': 220, 'masslock': 16,
        'core': (7, 6, 5, 4, 7, 6, 5),
        'hardpoints': (3, 3, 3, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (5, ''), (5, ''), (4, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'krait_phantom': {
        'name': 'Krait Phantom', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 2, 'hull_mass': 270.0, 'fuel_capacity': 32, 'max_cargo': 190,
        'crew': 2, 'top_speed': 250, 'boost_speed': 350, 'base_shield': 200, 'base_armour': 180, 'masslock': 14,
        'core': (7, 6, 5, 4, 7, 6, 5),
        'hardpoints': (3, 3, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (5, ''), (5, ''), (3, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'mamba': {
        'name': 'Mamba', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 2, 'hull_mass': 250.0, 'fuel_capacity': 8, 'max_cargo': 66,
        'crew': 2, 'top_speed': 310, 'boost_speed': 380, 'base_shield': 270, 'base_armour': 230, 'masslock': 12,
        'core': (6, 5, 4, 4, 6, 4, 3),
        'hardpoints': (4, 3, 3, 1, 1), 'utilities': 6,
        'optional': ((5, ''), (4, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'mandalay': {
        'name': 'Mandalay', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 2, 'hull_mass': 230.0, 'fuel_capacity': 32, 'max_cargo': 154,
        'crew': 2, 'top_speed': 280, 'boost_speed': 350, 'base_shield': 220, 'base_armour': 230, 'masslock': 11,
        'core': (5, 5, 5, 4, 5, 5, 5),
        'hardpoints': (2, 2, 2, 2, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'orca': {
        'name': 'Orca', 'manufacturer': 'Saud Kruger',
        'pad_size': 3, 'hull_mass': 290.0, 'fuel_capacity': 32, 'max_cargo': 194,
        'crew': 2, 'top_speed': 300, 'boost_speed': 380, 'base_shield': 220, 'base_armour': 220, 'masslock': 16,
        'core': (5, 6, 5, 6, 5, 4, 5),
        'hardpoints': (3, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (5, ''), (5, ''), (5, ''), (4, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'panther_clipper': {
        'name': 'Panther Clipper MkII', 'manufacturer': 'Zorgon Peterson',
        'pad_size': 3, 'hull_mass': 1200.0, 'fuel_capacity': 128, 'max_cargo': 1046,
        'crew': 4, 'top_speed': 181, 'boost_speed': 250, 'base_shield': 350, 'base_armour': 620, 'masslock': 27,
        'core': (8, 8, 7, 5, 7, 5, 7),
        'hardpoints': (3, 3, 2, 2, 2, 2, 1, 1, 1, 1), 'utilities': 6,
        'optional': ((8, 'cargo'), (8, ''), (7, 'cargo'), (7, ''), (6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (4, ''), (2, ''), (1, '')),
    },
    'python': {
        'name': 'Python', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 2, 'hull_mass': 350.0, 'fuel_capacity': 32, 'max_cargo': 294,
        'crew': 2, 'top_speed': 230, 'boost_speed': 300, 'base_shield': 260, 'base_armour': 260, 'masslock': 17,
        'core': (7, 6, 5, 4, 7, 6, 5),
        'hardpoints': (3, 3, 3, 2, 2), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (4, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'python_mk2': {
        'name': 'Python MkII', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 2, 'hull_mass': 450.0, 'fuel_capacity': 16, 'max_cargo': 96,
        'crew': 2, 'top_speed': 256, 'boost_speed': 345, 'base_shield': 335, 'base_armour': 280, 'masslock': 17,
        'core': (6, 6, 5, 4, 6, 5, 4),
        'hardpoints': (3, 3, 3, 3, 2, 2), 'utilities': 6,
        'optional': ((6, ''), (4, ''), (3, ''), (2, ''), (1, ''), (1, '')),
    },
    'sidewinder': {
        'name': 'Sidewinder', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 25.0, 'fuel_capacity': 2, 'max_cargo': 16,
        'crew': 1, 'top_speed': 220, 'boost_speed': 320, 'base_shield': 40, 'base_armour': 60, 'masslock': 6,
        'core': (2, 2, 2, 1, 1, 1, 1),
        'hardpoints': (1, 1), 'utilities': 2,
        'optional': ((2, ''), (2, ''), (1, ''), (1, ''), (1, ''), (1, '')),
    },
    'type_10': {
        'name': 'Type-10 Defender', 'manufacturer': 'Lakon',
        'pad_size': 3, 'hull_mass': 1200.0, 'fuel_capacity': 64, 'max_cargo': 534,
        'crew': 4, 'top_speed': 179, 'boost_speed': 219, 'base_shield': 320, 'base_armour': 580, 'masslock': 26,
        'core': (8, 7, 7, 5, 7, 4, 6),
        'hardpoints': (3, 3, 3, 3, 2, 2, 2, 1, 1), 'utilities': 8,
        'optional': ((8, ''), (7, ''), (6, ''), (5, ''), (4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (5, 'military'), (5, 'military'), (1, '')),
    },
    'type_11': {
        'name': 'Type-11 Prospector', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 320.0, 'fuel_capacity': 32, 'max_cargo': 288,
        'crew': 3, 'top_speed': 272, 'boost_speed': 367, 'base_shield': 275, 'base_armour': 350, 'masslock': 16,
        'core': (6, 5, 5, 3, 7, 3, 5),
        'hardpoints': (3, 2, 2, 2, 1, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, 'limpets'), (5, 'fighter'), (4, ''), (3, ''), (2, ''), (1, ''), (1, '')),
    },
    'type_6': {
        'name': 'Type-6 Transporter', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 155.0, 'fuel_capacity': 16, 'max_cargo': 114,
        'crew': 1, 'top_speed': 220, 'boost_speed': 350, 'base_shield': 90, 'base_armour': 180, 'masslock': 8,
        'core': (3, 4, 4, 2, 3, 2, 4),
        'hardpoints': (1, 1), 'utilities': 3,
        'optional': ((5, ''), (5, ''), (4, ''), (4, ''), (3, ''), (2, ''), (2, ''), (1, '')),
    },
    'type_7': {
        'name': 'Type-7 Transporter', 'manufacturer': 'Lakon',
        'pad_size': 3, 'hull_mass': 350.0, 'fuel_capacity': 32, 'max_cargo': 310,
        'crew': 1, 'top_speed': 180, 'boost_speed': 300, 'base_shield': 155, 'base_armour': 340, 'masslock': 10,
        'core': (5, 5, 5, 4, 4, 3, 5),
        'hardpoints': (1, 1, 1, 1), 'utilities': 4,
        'optional': ((6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (5, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'type_8': {
        'name': 'Type-8 Transporter', 'manufacturer': 'Lakon',
        'pad_size': 2, 'hull_mass': 400.0, 'fuel_capacity': 32, 'max_cargo': 406,
        'crew': 1, 'top_speed': 200, 'boost_speed': 340, 'base_shield': 228, 'base_armour': 440, 'masslock': 18,
        'core': (5, 5, 5, 3, 4, 3, 5),
        'hardpoints': (2, 1, 1, 1, 1, 1), 'utilities': 4,
        'optional': ((7, ''), (6, ''), (6, ''), (6, ''), (5, ''), (5, ''), (4, ''), (2, ''), (1, '')),
    },
    'type_9': {
        'name': 'Type-9 Heavy', 'manufacturer': 'Lakon',
        'pad_size': 3, 'hull_mass': 850.0, 'fuel_capacity': 64, 'max_cargo': 790,
        'crew': 4, 'top_speed': 130, 'boost_speed': 200, 'base_shield': 240, 'base_armour': 480, 'masslock': 16,
        'core': (6, 7, 6, 5, 6, 4, 6),
        'hardpoints': (2, 2, 2, 1, 1), 'utilities': 4,
        'optional': ((8, ''), (8, ''), (7, ''), (6, ''), (5, ''), (4, ''), (4, ''), (3, ''), (3, ''), (2, ''), (1, '')),
    },
    'viper_mk3': {
        'name': 'Viper MkIII', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 50.0, 'fuel_capacity': 4, 'max_cargo': 26,
        'crew': 1, 'top_speed': 320, 'boost_speed': 400, 'base_shield': 105, 'base_armour': 70, 'masslock': 7,
        'core': (3, 3, 3, 2, 3, 3, 2),
        'hardpoints': (2, 2, 1, 1), 'utilities': 2,
        'optional': ((3, ''), (3, ''), (3, 'military'), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'viper_mk4': {
        'name': 'Viper MkIV', 'manufacturer': 'Faulcon DeLacy',
        'pad_size': 1, 'hull_mass': 190.0, 'fuel_capacity': 16, 'max_cargo': 54,
        'crew': 1, 'top_speed': 270, 'boost_speed': 340, 'base_shield': 150, 'base_armour': 150, 'masslock': 7,
        'core': (4, 4, 4, 2, 3, 3, 4),
        'hardpoints': (2, 2, 1, 1), 'utilities': 2,
        'optional': ((4, ''), (4, ''), (3, ''), (3, 'military'), (2, ''), (2, ''), (1, ''), (1, ''), (1, '')),
    },
    'vulture': {
        'name': 'Vulture', 'manufacturer': 'Core Dynamics',
        'pad_size': 1, 'hull_mass': 230.0, 'fuel_capacity': 8, 'max_cargo': 60,
        'crew': 2, 'top_speed': 210, 'boost_speed': 340, 'base_shield': 240, 'base_armour': 160, 'masslock': 10,
        'core': (4, 5, 4, 3, 5, 4, 3),
        'hardpoints': (3, 3), 'utilities': 4,
        'optional': ((5, ''), (5, 'military'), (4, ''), (2, ''), (1, ''), (1, ''), (1, ''), (1, '')),
    },
}
