"""Bundled offline reference data for ED capabilities.

Currently the engineering tables (`materials.json`, `blueprints.json`) that back the
blueprint / material-sourcing capability (issue #66). They are DERIVED from public
community data and regenerated by `regen_engineering_data.py` — never hand-edited.
"""
