"""Space chatter (C6) — context-driven ambient lines, template-pool driven with fact gating.

Chatter categories are cues (C2) the C3 driver picks and governs. Each declares its eligible
game states, target bus, cooldown, and a curated phrasing pool. The one rule that keeps the
companion honest (the help discipline, applied to audio):

  * fact_bearing cues speak ONLY from their vetted pool — deterministic rotation, never the LLM.
    A fact-bearing line could assert something checkable, so a human wrote every option.
  * flavor cues (fact_bearing=False) may have a line GENERATED by the LLM, but only pure
    atmosphere with nothing checkable; a validator rejects anything with a number or a proper
    noun and the player falls back to the pool. The LLM only ever yields text that is validated
    then routed — it is never in the realtime audio path.

Governed by C3 (cooldowns + the global rate cap) so chatter never over-talks. On top of that,
chatter is POPULATED-ONLY and POPULATION-SCALED: every cue is eligible only in an inhabited
system, and how often it actually speaks is throttled by a min/max seconds-between-lines window
that slides with the system's population (a busy hub chatters near the min gap; a sparse outpost
near the max). See `chatter_interval` + the `min_interval` gate on `ChatterPlayer`.
"""
from __future__ import annotations

import math
import re
import time
from typing import Callable, Optional

from .buses import COMMS, COVAS
from .cues import PERSONA, Cue
from .eligibility import POPULATED

_WORD = re.compile(r"[A-Za-z']+")
_SENTENCE = re.compile(r"[.!?]+")


def chatter_interval(min_s: float, max_s: float, population: Optional[float],
                     full_population: float) -> Optional[float]:
    """The current required seconds-BETWEEN-chatter-lines, scaled by system population.

    A dense system (population >= `full_population`) chatters at the fast `min_s` gap; a sparse
    one stretches toward the slow `max_s` gap; an UNPOPULATED (or unknown) system returns None =
    "never" (chatter is populated-only anyway, so this is a belt-and-braces gate). The scale is
    logarithmic because ED populations span many orders of magnitude (a few thousand to tens of
    billions), so a linear map would peg almost everything to the sparse end. Pure + testable."""
    if population is None or population <= 0:
        return None
    lo, hi = (min_s, max_s) if min_s <= max_s else (max_s, min_s)
    full = full_population if full_population and full_population > 1 else 10.0
    factor = math.log10(max(population, 1.0)) / math.log10(full)
    factor = 0.0 if factor < 0.0 else (1.0 if factor > 1.0 else factor)
    return hi - factor * (hi - lo)


def _has_proper_noun(text: str) -> bool:
    """Any Title-case / ALL-CAPS token that isn't sentence-initial — i.e. a named entity (a
    system, station, ship, or person). Its presence makes a 'musing' checkable."""
    for sentence in _SENTENCE.split(text or ""):
        toks = _WORD.findall(sentence)
        for i, tok in enumerate(toks):
            if i == 0 or len(tok) < 2:
                continue
            if tok[0].isupper() and (tok.istitle() or tok.isupper()):
                return True
    return False


def is_flavor_safe(text: str) -> bool:
    """A flavor musing must assert NOTHING checkable: no numbers, no proper nouns (named
    systems/stations/ships/people). Pure. Rejected flavor falls back to the curated pool."""
    t = text or ""
    if not t.strip():
        return False
    if any(ch.isdigit() for ch in t):
        return False
    return not _has_proper_noun(t)


def build_chatter_prompt(cue: Cue) -> str:
    """Prompt for a flavor (fact_bearing=False) musing. The validator is the real guard, but the
    prompt still states the rules and offers the pool as tone examples."""
    examples = " / ".join(cue.phrasings[:3]) if cue.phrasings else "(quiet, atmospheric)"
    return (
        "You voice a brief, ambient in-character musing for an Elite Dangerous companion. Say ONE "
        "short line of pure atmosphere — NO specific facts, NO names, NO numbers, nothing "
        "checkable. Just mood.\n"
        f"Tone examples: {examples}\n"
        "Reply with ONLY the line."
    )


class ChatterPlayer:
    """The C3 driver's `play` callback for chatter cues. Chooses a line and routes it to the
    cue's bus, advancing the pool rotation deterministically.

    Injected seams (offline-testable):
      * `speak(text, bus) -> bool` — routes a line to a bus (the app wires this to the mixer),
        returning True only if playback started;
      * `generate(prompt) -> str` — the LLM flavor generator (None => pool-only). Used ONLY for
        fact_bearing=False cues, and only if the result passes `is_flavor_safe`.
      * `min_interval() -> float | None` — the current required seconds between chatter lines
        (see `chatter_interval`); None => no extra gate. This is the FREQUENCY control on top of
        the C3 governor: a line is suppressed (and, crucially, does NOT burn the governor budget,
        since a False return leaves the cue un-fired) until this much time has elapsed. `clock`
        supplies monotonic time so the gate is testable.
    """

    def __init__(
        self,
        speak: Callable[[str, str], bool],
        *,
        generate: Optional[Callable[[str], str]] = None,
        min_interval: Optional[Callable[[], Optional[float]]] = None,
        clock: Callable[[], float] = time.monotonic,
        log: Optional[Callable[[str], None]] = None,
    ) -> None:
        self._speak = speak
        self._generate = generate
        self._min_interval = min_interval
        self._clock = clock
        self._log = log
        self._rot: dict[str, int] = {}   # per-cue pool rotation pointer
        self._last_spoken: float = float("-inf")  # monotonic time of the last chatter line

    def line_for(self, cue: Cue) -> tuple[str, str]:
        """(text, source) where source is 'flavor' (validated LLM) or 'pool' (deterministic
        rotation). A fact_bearing cue NEVER reaches the generator."""
        if not cue.fact_bearing and self._generate is not None:
            try:
                candidate = (self._generate(build_chatter_prompt(cue)) or "").strip()
            except Exception:  # noqa: BLE001 — a generator failure degrades to the pool
                candidate = ""
            if candidate and is_flavor_safe(candidate):
                return candidate, "flavor"
        # fact-bearing, no generator, or rejected flavor -> the curated pool, rotated.
        return cue.phrasing_at(self._rot.get(cue.name, 0)), "pool"

    def _frequency_ok(self, now: float) -> bool:
        """The population-scaled frequency gate: True unless a chatter line spoke too recently.
        Checked BEFORE `line_for` so a suppressed turn never touches the (paid) LLM generator."""
        if self._min_interval is None:
            return True
        gap = self._min_interval()
        if gap is None:      # unknown/unpopulated -> no chatter this turn
            return False
        return (now - self._last_spoken) >= gap

    def __call__(self, cue: Cue) -> bool:
        now = self._clock()
        if not self._frequency_ok(now):
            return False
        text, source = self.line_for(cue)
        if not text.strip():
            return False
        started = bool(self._speak(text, cue.bus))
        if started:
            self._last_spoken = now
            if source == "pool":
                self._rot[cue.name] = self._rot.get(cue.name, 0) + 1
            if self._log is not None:
                self._log(f"chatter[{source}] {cue.name} -> {cue.bus}: {text}")
        return started


# ---- the shipped chatter categories ---------------------------------------------------------
# POPULATED-ONLY: every chatter cue is eligible only in an inhabited system (Population > 0). The
# ambient radio buzz is the sound of *other people* — station traffic, patrols, market talk — so
# out in the empty black there is deliberately nothing to say. The ambient lines ride the Comms bus
# (radio-flavored) with a random cast voice; the `populated_musing` cue is different — it's the
# COMPANION'S OWN observation ("nice to have some company out here"), an "our"-perspective line, so
# it's tagged `voice_role=PERSONA` and the audio layer speaks it in COVAS's own voice on the clean
# COVAS bus (issue #57). All are throttled by their own cooldown plus the global C3 governor, then
# frequency-gated + population-scaled by `chatter_interval` (see ChatterPlayer.min_interval).
def chatter_cues() -> list[Cue]:
    return [
        Cue(
            "station_traffic", COMMS, {POPULATED}, cooldown_s=90.0, fact_bearing=True,
            phrasings=(
                "Traffic's steady around here.",
                "Plenty of ships on the scope today.",
                "Docking lanes are busy.",
                "Comms are lively this shift.",
            ),
        ),
        Cue(
            "system_patrol", COMMS, {POPULATED}, cooldown_s=110.0, fact_bearing=True,
            phrasings=(
                "Security's running patrols nearby.",
                "Authority vessels holding station.",
                "Local patrol's keeping the lanes clear.",
            ),
        ),
        Cue(
            "market_buzz", COMMS, {POPULATED}, cooldown_s=130.0, fact_bearing=True,
            phrasings=(
                "Haulers coming and going all day.",
                "Trade's moving briskly hereabouts.",
                "Cargo lanes are humming.",
            ),
        ),
        Cue(
            # OUR-perspective: the companion musing to the Commander -> persona voice, clean bus.
            "populated_musing", COVAS, {POPULATED}, cooldown_s=150.0,
            voice_role=PERSONA,
            fact_bearing=False,   # pure atmosphere -> LLM permitted (validated), pool fallback
            phrasings=(
                "Nice to have some company out here.",
                "Feels good to be somewhere lived-in.",
                "Always a buzz around people.",
            ),
        ),
    ]


def register_chatter(registry) -> None:  # noqa: ANN001 — a CueRegistry
    """Register every shipped chatter cue with the cue registry."""
    for cue in chatter_cues():
        registry.register(cue)
